global_config:
  ip: '127.0.0.1'
  port: '9099'
  num_workers: 40

det_models:
  - photo_ids: [ 2,22 ]
    device_id: { 0: '3', 1: '3' }
    weight_path: '../weights/FC_YOUMO_M14.pt'
    filter: null
    enhance: False
    analyze_defects: ['juchi', 'ymbj', 'bengbian', 'ymkl']
    class_dict: {  0: 'juchi', 1: 'ymbj', 2: 'bengbian', 3: 'ymkl' }
    conf_thres: 0.5
    iou_thres: 0.45
    resize: null
    model_copies: 1

  - photo_ids: [ 1 ]
    device_id: { 0: '3', 1: '3' }
    weight_path: '../weights/FC_DM_M18.pt'
    filter: null
    enhance: False
    analyze_defects: [ 'huashang', 'cashang']
    class_dict: {  0: 'huashang', 1: 'cashang' }
    conf_thres: 0.5
    iou_thres: 0.45
    resize: null
    model_copies: 1

  - photo_ids: [ 4,7,8,11,12,15,16,19,20 ]
    device_id: { 0: '3', 1: '3' }
    weight_path: '../weights/FC_CM_M13.pt'
    filter: null
    enhance: False
    analyze_defects:  ['huashang', 'cashang', 'zangwu']
    class_dict: { 0: 'huashang', 1: 'cashang', 2: 'zangwu'}
    conf_thres: 0.5
    iou_thres: 0.45
    resize: null
    model_copies: 1

  - photo_ids: [ 1,4 ]
    device_id: { 0: '3', 1: '3' }
    weight_path: '../weights/FC_DZ_M9.pt'
    filter: null
    enhance: False
    analyze_defects: ['dianzhuang', 'zangwu']
    class_dict: { 0: 'dianzhuang', 1: 'zangwu', 2: 'huichen' }
    conf_thres: 0.85
    iou_thres: 0.45
    resize: null
    model_copies: 1

  - photo_ids: [ 4 ]
    device_id: { 0: '3', 1: '3' }
    weight_path: '../weights/FC_WMT_M6.pt'
    filter: null
    enhance: False
    analyze_defects: ['wmt']
    class_dict: { 0: 'wmt' }
    conf_thres: 0.5
    iou_thres: 0.45
    resize: null
    model_copies: 1

  - photo_ids: [ 9,13,17,21 ]
    device_id: { 0: '3', 1: '3' }
    weight_path: '../weights/FC_DW_M7.pt'
    filter: null
    enhance: False
    analyze_defects: ['daowen', 'daowen1']
    class_dict: { 0: 'daowen', 1: 'daowen1' }
    conf_thres: 0.5
    iou_thres: 0.45
    resize: null
    model_copies: 1

cls_models: [ ]
post_cls_models: [ ]
